RESEARCH_DOMAINS = [
    "Artificial Intelligence",
    "Machine Learning",
    "Healthcare",
    "Climate Science",
    "Cybersecurity",
    "Quantum Computing",
    "Robotics",
    "Neuroscience",
    "Education",
    "Environmental Science",
    "Materials Science",
    "Bioinformatics",
    "Social Science",
    "Data Science",
    "Physics",
    "Chemistry",
    "Biology",
    "Engineering",
    "Mathematics",
    "Computer Science",
    "Cyberinfrastructure",
    "Plasma Physics",
    "Space Science",
    "Geosciences",
    "Optics & Photonics",
    "Advanced Manufacturing",
    "Social Science",
    "Behavioral Science",
    "Economic Science",
    "Astrophysics",
    "Polar Science",
    "Ocean Sciences",
]

METHODS = [
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "Reinforcement Learning",
    "Statistical Analysis",
    "Survey Research",
    "Clinical Trials",
    "Simulation",
    "Optimization",
    "Network Analysis",
    "Remote Sensing",
    "Genomics",
    "Modeling",
    "Open Science",
    "Cloud Computing",
    "High Performance Computing",
    "Distributed Systems",
    "Ethnography",
]

POPULATIONS = [
    "Children",
    "Elderly",
    "Underserved Communities",
    "Rural Communities",
    "Veterans",
    "Students",
    "Researchers",
    "Clinicians",
    "Small Businesses",
    "Minorities",
    "Women",
    "Low-Income Populations",
]

SPONSOR_THEMES = [
    "Open Source",
    "Workforce Development",
    "Economic Growth",
    "National Security",
    "Public Health",
    "Digital Transformation",
    "STEM Education",
    "Broadening Participation",
    "Infrastructure",
    "Innovation",
    "Sustainability",
    "Equity and Inclusion",
]

RULE_KEYWORDS = {
    "research_domains": {
        "Artificial Intelligence": ["artificial intelligence", "ai ", "ai-", "intelligent system"],
        "Machine Learning": ["machine learning", "deep learning", "neural network", "ml "],
        "Healthcare": ["health", "medical", "clinical", "patient", "disease", "biomedical"],
        "Climate Science": ["climate", "global warming", "greenhouse", "carbon", "weather"],
        "Cybersecurity": ["cybersecurity", "cyber security", "security", "encryption", "privacy"],
        "Quantum Computing": ["quantum"],
        "Robotics": ["robot", "autonomous system", "drone"],
        "Neuroscience": ["neuroscience", "brain", "neural", "cognitive"],
        "Education": ["education", "learning outcome", "student", "curriculum", "pedagogy"],
        "Environmental Science": ["environment", "ecosystem", "biodiversity", "ecology"],
        "Materials Science": ["materials", "nanomaterial", "polymer", "semiconductor"],
        "Bioinformatics": ["bioinformatics", "genomic", "proteomics", "sequencing"],
        "Data Science": ["data science", "analytics", "big data", "data mining"],
    },
    "methods": {
        "Deep Learning": ["deep learning", "neural network", "transformer", "cnn", "rnn"],
        "Natural Language Processing": ["nlp", "natural language", "text mining", "language model"],
        "Computer Vision": ["computer vision", "image recognition", "object detection"],
        "Reinforcement Learning": ["reinforcement learning", "reward", "policy gradient"],
        "Statistical Analysis": ["statistical", "regression", "hypothesis testing"],
        "Survey Research": ["survey", "questionnaire", "interview"],
        "Clinical Trials": ["clinical trial", "randomized", "placebo"],
        "Simulation": ["simulation", "modeling", "computational model"],
        "Optimization": ["optimization", "objective function", "gradient"],
        "Genomics": ["genome", "genomic", "sequencing", "dna"],
    },
    "populations": {
        "Children": ["children", "child", "pediatric", "youth"],
        "Elderly": ["elderly", "older adult", "aging", "senior"],
        "Underserved Communities": ["underserved", "disadvantaged", "marginalized"],
        "Rural Communities": ["rural"],
        "Veterans": ["veteran", "military"],
        "Students": ["student", "undergraduate", "graduate"],
        "Small Businesses": ["small business", "startup", "entrepreneur"],
        "Minorities": ["minority", "underrepresented", "hispanic", "african american"],
        "Women": ["women", "gender", "female"],
    },
    "sponsor_themes": {
        "Open Source": ["open source", "open-source", "open software"],
        "Workforce Development": ["workforce", "job training", "career"],
        "National Security": ["national security", "defense", "homeland"],
        "Public Health": ["public health", "epidemic", "pandemic", "disease prevention"],
        "Digital Transformation": ["digital", "digitization", "e-government"],
        "STEM Education": ["stem", "science education", "math education"],
        "Broadening Participation": ["broadening participation", "diversity", "inclusion"],
        "Innovation": ["innovation", "breakthrough", "novel", "emerging"],
        "Sustainability": ["sustainable", "sustainability", "renewable", "clean energy"],
        "Equity and Inclusion": ["equity", "inclusion", "accessible"],
    },
}

# Update the keywords to include the newly added domains too
RULE_KEYWORDS["research_domains"].update({
    "Cyberinfrastructure": ["cyberinfrastructure", "hpc", "computing infrastructure", "data infrastructure"],
    "Plasma Physics": ["plasma science", "plasma physics", "plasma chemistry", "eclipse"],
    "Space Science": ["space science", "astrophysics", "astronomy", "telescope"],
    "Geosciences": ["geosciences", "earth science", "geology", "oceanography"],
    "Open Science": ["open science", "open access", "open data"],
    "Information Science": ["information science", "computing", "cise"],
})

RULE_KEYWORDS["methods"].update({
    "Open Science": ["open science", "open access", "data sharing", " FAIR data"],
    "Cloud Computing": ["cloud computing", "cloud storage", "aws", "gcp", "azure", "distributed cloud"],
    "High Performance Computing": ["high performance computing", "hpc", "supercomputing"],
})
